version: '3.4'

services:
#  itentikatest.eventprocessor:
#    image: ${DOCKER_REGISTRY-}itentikatesteventprocessor
#    build:
#      context: .
#      dockerfile: Systems/ITentikaTest.EventProcessor/Dockerfile
      
  itentikatest.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - 5432:5432
