version: '3.4'

services:
#  itentikatest.eventprocessor:
#    image: ${DOCKER_REGISTRY-}itentikatesteventprocessor
#    build:
#      context: .
#      dockerfile: Systems/ITentikaTest.EventProcessor/Dockerfile
  
  itentikatest.eventpublisher:
    image: itentikatesteventpublisher:latest
    build:
      context: .
      dockerfile: Systems/ITentikaTest.EventPublisher/Dockerfile
        
  itentikatest.postgres:
    image: postgres:latest